/*
Copyright 2017 Jetstack Ltd.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// This file was automatically generated by informer-gen

package v1alpha1

import (
	navigator_v1alpha1 "github.com/jetstack/navigator/pkg/apis/navigator/v1alpha1"
	versioned "github.com/jetstack/navigator/pkg/client/clientset/versioned"
	internalinterfaces "github.com/jetstack/navigator/pkg/client/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/jetstack/navigator/pkg/client/listers/navigator/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
	time "time"
)

// LeaderLockInformer provides access to a shared informer and lister for
// LeaderLocks.
type LeaderLockInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.LeaderLockLister
}

type leaderLockInformer struct {
	factory internalinterfaces.SharedInformerFactory
	filter  internalinterfaces.FilterFunc
}

// NewLeaderLockInformer constructs a new informer for LeaderLock type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewLeaderLockInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	filter := internalinterfaces.NamespaceFilter(namespace)
	return NewFilteredLeaderLockInformer(client, filter, resyncPeriod, indexers)
}

// NewFilteredLeaderLockInformer constructs a new informer for LeaderLock type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredLeaderLockInformer(client versioned.Interface, filter internalinterfaces.FilterFunc, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				namespace := filter(&options)
				return client.NavigatorV1alpha1().LeaderLocks(namespace).List(options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				namespace := filter(&options)
				return client.NavigatorV1alpha1().LeaderLocks(namespace).Watch(options)
			},
		},
		&navigator_v1alpha1.LeaderLock{},
		resyncPeriod,
		indexers,
	)
}

func (f *leaderLockInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredLeaderLockInformer(client, f.filter, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc})
}

func (f *leaderLockInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&navigator_v1alpha1.LeaderLock{}, f.defaultInformer)
}

func (f *leaderLockInformer) Lister() v1alpha1.LeaderLockLister {
	return v1alpha1.NewLeaderLockLister(f.Informer().GetIndexer())
}
